include: package:mews_pedantic/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.rpc.dart"
  errors:
    invalid_annotation_target: ignore

dart_code_metrics:
  rules:
    avoid-barrel-files: false
    avoid-missing-interpolation: false
    avoid-passing-self-as-argument: false
